# **NumPy Tutorial**

Writer: **Rupak Ganvir**

Contact: **rupakganvir12@gmail.com**

## **Importing NumPy**

In [117]:
import numpy as np

## **Basics**

In [118]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [119]:
b = np.array([[1,2,3,7],[4,5,6,8]])
print(b)

[[1 2 3 7]
 [4 5 6 8]]


In [120]:
# Dimension of an array

print(a.ndim)
print(b.ndim)

1
2


In [121]:
# Shape of an array

print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [122]:
# Data type

print(a.dtype)
print(b.dtype)

int32
int64


In [123]:
# Get size

print(a.itemsize)
print(b.itemsize)

4
8


In [124]:
# Get total size

print(a.nbytes)
print(b.nbytes)

12
64


## **Accessing/Changing specific elements, rows, columns, etc**

In [125]:
n = np.array([[1,2,3,7,8,9,10],[4,5,6,8,11,12,13]])
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6  8 11 12 13]]


In [126]:
# Get a specific element

n[0, 2]
n[1, -5]

np.int64(6)

In [127]:
# Get a specific row

n[1, :]

array([ 4,  5,  6,  8, 11, 12, 13])

In [128]:
# Get a specific column

n[:, 1]

array([2, 5])

In [129]:
# Getting more complicated thing (startIndex:endIndex:stepSize)

n[0, 1:-1:2] # Get the first row, starting from index 1 to the end, with a step size of 2

array([2, 7, 9])

In [130]:
# Change any element

n[1,3] = 14
print(n)


# Change columns

n[:,2] = 1
print(n)
# or
n[:,2] = [11,22]
print(n)


# Change rows

n[1,:] = 1
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6 14 11 12 13]]
[[ 1  2  1  7  8  9 10]
 [ 4  5  1 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 4  5 22 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 1  1  1  1  1  1  1]]


In [131]:
# 3D array

m = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [132]:
# Get a specific element

print(m[1,1,1]) # In 1st row, 1st column, 1st element (Indexing starts from 0)
print(m[:,1,:]) # Get the 1st column of all rows
print(m[:,1,:2]) # Get the 1st column of all rows, but only the first 2 elements

11
[[ 4  5  6]
 [10 11 12]]
[[ 4  5]
 [10 11]]


In [133]:
# Replace

m[:,1,:] = 20
print(m)

m[:,1,:] = [21,22,23]
print(m)

[[[ 1  2  3]
  [20 20 20]]

 [[ 7  8  9]
  [20 20 20]]]
[[[ 1  2  3]
  [21 22 23]]

 [[ 7  8  9]
  [21 22 23]]]


## **Initializing different types of arrays**

In [134]:
# All zeroes

print(np.zeros(5)) # 1D array of zeros
print(np.zeros((5,5))) # 2D array of zeros
print(np.zeros((2,2,3))) # 3D array of zeros

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [135]:
# All ones

print(np.ones(5)) # 1D array of ones
print(np.ones((5,5))) # 2D array of ones
print(np.ones((3,2,2))) # 3D array of ones

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [136]:
# Any other number

print(np.full((5,5), 99)) # 2D array of 99s
print(np.full((5,5), 3.14)) # 2D array of 3.14s
print(np.full((2,3,4), 99)) # 3D array of 99s


# Full_like
print(np.full_like(m,4)) # Create an array with the same shape as m, but filled with 4s

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[[[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]

 [[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]]
[[[4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]]]


In [137]:
# Random Decimal Numbers

print(np.random.rand(4,2,3)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

print(np.random.random_sample(a.shape)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). The shape is taken from array a.

[[[0.54496543 0.23798812 0.28228871]
  [0.00484353 0.38125755 0.9649383 ]]

 [[0.48140212 0.64284007 0.78739344]
  [0.45616666 0.84619746 0.14653702]]

 [[0.32502168 0.10863589 0.05476097]
  [0.29921143 0.92473779 0.90275119]]

 [[0.13921017 0.04812582 0.95877003]
  [0.55202707 0.39994159 0.81881986]]]
[0.09729812 0.55021374 0.26463439]


In [138]:
# Random Integer Value

print(np.random.randint(7, size =(3,3))) # Create an array of the given shape and populate it with random integers from 0 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.
print(np.random.randint(-2,7, size =(3,3))) # Create an array of the given shape and populate it with random integers from -2 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.

[[4 1 5]
 [5 3 0]
 [0 4 6]]
[[ 5 -1  5]
 [ 0 -1  5]
 [ 6 -1  1]]


In [139]:
# Identity matrix

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [140]:
# Repet an array

arr = np.array([[1,2,3]]) # Create a 2D array with one row and three columns. The shape of this array is (1, 3), meaning it has 1 row and 3 columns. The elements of the array are 1, 2, and 3.

r1 = np.repeat(arr,3) # Repeat each element of arr 3 times
print(r1)

r2 = np.repeat(arr,3, axis=0) # Repeat each element of arr 3 times along the first axis (rows)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [141]:
# Exercise : Make a 5x5 array with all outer elements are one and inner elements are zero and the center element is 9

# Solution :
output = np.ones((5, 5), dtype='int32') # Create a 5x5 array filled with ones, with data type int32
output[1:4, 1:4] = 0 # Set the inner 3x3 block to zero
output[2, 2] = 9 # Set the center element to 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [142]:
# Be careful while copying arrays

a = np.array([1,2,3])
b = a # This does not create a new array, but rather a reference to the same array in memory. Changes to b will affect a and vice versa.
b[0] = 5
print(b)
print(a) # This will also show the change because b is a reference to a

# So the right way to copy:
a = np.array([1,2,3])
b = a.copy()
b[0] = 5
print(b)
print(a)

[5 2 3]
[5 2 3]
[5 2 3]
[1 2 3]


## **MATHEMATICS**

In [143]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [144]:
print(a+2) # Also can use a += 2 to add 2 to each element of the array a
print(a-2) # Also can use a -= 2 to subtract 2 from each element of the array a
print(a*2) # Also can use a *= 2 to multiply each element of the array a by 2
print(a/2) # Also can use a /= 2 to divide each element of the array a by 2
print(a**2) # It is the same as a*a, which multiplies each element of the array a by itself, resulting in an array where each element is the square of the corresponding element in a.

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [145]:
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

# Take sin & cos of all the values
print(np.sin(a))
print(np.cos(a))
print(np.sin(b))
print(np.cos(b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[-0.95892427 -0.2794155   0.6569866   0.98935825]
[ 0.28366219  0.96017029  0.75390225 -0.14550003]


##### There are mpre things you can explore. You can check this: https://numpy.org/doc/2.4/reference/routines.math.html

### **Linear Algebra**