# **NumPy Tutorial**

Author: **Rupak Ganvir**

## **Importing NumPy**

In [106]:
import numpy as np

## **Basics**

In [107]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [108]:
b = np.array([[1,2,3,7],[4,5,6,8]])
print(b)

[[1 2 3 7]
 [4 5 6 8]]


In [109]:
# Dimension of an array

print(a.ndim)
print(b.ndim)

1
2


In [110]:
# Shape of an array

print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [111]:
# Data type

print(a.dtype)
print(b.dtype)

int32
int64


In [112]:
# Get size

print(a.itemsize)
print(b.itemsize)

4
8


In [113]:
# Get total size

print(a.nbytes)
print(b.nbytes)

12
64


## **Accessing/Changing specific elements, rows, columns, etc**

In [114]:
n = np.array([[1,2,3,7,8,9,10],[4,5,6,8,11,12,13]])
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6  8 11 12 13]]


In [115]:
# Get a specific element

n[0, 2]
n[1, -5]

np.int64(6)

In [116]:
# Get a specific row

n[1, :]

array([ 4,  5,  6,  8, 11, 12, 13])

In [117]:
# Get a specific column

n[:, 1]

array([2, 5])

In [118]:
# Getting more complicated thing (startIndex:endIndex:stepSize)

n[0, 1:-1:2] # Get the first row, starting from index 1 to the end, with a step size of 2

array([2, 7, 9])

In [119]:
# Change any element

n[1,3] = 14
print(n)


# Change columns

n[:,2] = 1
print(n)
# or
n[:,2] = [11,22]
print(n)


# Change rows

n[1,:] = 1
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6 14 11 12 13]]
[[ 1  2  1  7  8  9 10]
 [ 4  5  1 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 4  5 22 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 1  1  1  1  1  1  1]]


In [120]:
# 3D array

m = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [121]:
# Get a specific element

print(m[1,1,1]) # In 1st row, 1st column, 1st element (Indexing starts from 0)
print(m[:,1,:]) # Get the 1st column of all rows
print(m[:,1,:2]) # Get the 1st column of all rows, but only the first 2 elements

11
[[ 4  5  6]
 [10 11 12]]
[[ 4  5]
 [10 11]]


In [122]:
# Replace

m[:,1,:] = 20
print(m)

m[:,1,:] = [21,22,23]
print(m)

[[[ 1  2  3]
  [20 20 20]]

 [[ 7  8  9]
  [20 20 20]]]
[[[ 1  2  3]
  [21 22 23]]

 [[ 7  8  9]
  [21 22 23]]]


## **Initializing different types of arrays**

In [123]:
# All zeroes

print(np.zeros(5)) # 1D array of zeros
print(np.zeros((5,5))) # 2D array of zeros
print(np.zeros((2,2,3))) # 3D array of zeros

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [124]:
# All ones

print(np.ones(5)) # 1D array of ones
print(np.ones((5,5))) # 2D array of ones
print(np.ones((3,2,2))) # 3D array of ones

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [125]:
# Any other number

print(np.full((5,5), 99)) # 2D array of 99s
print(np.full((5,5), 3.14)) # 2D array of 3.14s
print(np.full((2,3,4), 99)) # 3D array of 99s


# Full_like
print(np.full_like(m,4)) # Create an array with the same shape as m, but filled with 4s

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[[[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]

 [[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]]
[[[4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]]]


In [126]:
# Random Decimal Numbers

print(np.random.rand(4,2,3)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

print(np.random.random_sample(a.shape)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). The shape is taken from array a.

[[[0.66588564 0.19976366 0.63730201]
  [0.74952366 0.39230676 0.80036446]]

 [[0.22957625 0.18763826 0.8236784 ]
  [0.01059461 0.78936047 0.40472777]]

 [[0.00785542 0.59112515 0.33060845]
  [0.1745653  0.84116671 0.46169096]]

 [[0.00303838 0.7198638  0.23386967]
  [0.23104922 0.854687   0.53065829]]]
[0.33537325 0.19421585 0.00991771]


In [127]:
# Random Integer Value

print(np.random.randint(7, size =(3,3))) # Create an array of the given shape and populate it with random integers from 0 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.
print(np.random.randint(-2,7, size =(3,3))) # Create an array of the given shape and populate it with random integers from -2 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.

[[0 2 3]
 [2 5 0]
 [1 6 6]]
[[-2 -2  3]
 [ 6  2  3]
 [-2  0  0]]


In [128]:
# Identity matrix

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [129]:
# Repeat an array

arr = np.array([[1,2,3]]) # Create a 2D array with one row and three columns. The shape of this array is (1, 3), meaning it has 1 row and 3 columns. The elements of the array are 1, 2, and 3.

r1 = np.repeat(arr,3) # Repeat each element of arr 3 times. Since arr is a 2D array with shape (1, 3), the repeat function will flatten it to a 1D array and repeat each element 3 times, resulting in a 1D array with 9 elements: [1, 1, 1, 2, 2, 2, 3, 3, 3].
print(r1)

r2 = np.repeat(arr,3, axis=0) # Repeat each element of arr 3 times along the first axis (rows)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


### **Exercise 1**
1) Make a 5x5 array with all outer elements are one and inner elements are zero and the center element is 9

In [130]:
# Solution :
output = np.ones((5, 5), dtype='int32') # Create a 5x5 array filled with ones, with data type int32
output[1:4, 1:4] = 0 # Set the inner 3x3 block to zero
output[2, 2] = 9 # Set the center element to 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [131]:
# Be careful while copying arrays

a = np.array([1,2,3])
b = a # This does not create a new array, but rather a reference to the same array in memory. Changes to b will affect a and vice versa.
b[0] = 5
print(b)
print(a) # This will also show the change because b is a reference to a

# So the right way to copy:
a = np.array([1,2,3])
b = a.copy()
b[0] = 5
print(b)
print(a)

[5 2 3]
[5 2 3]
[5 2 3]
[1 2 3]


## **MATHEMATICS**

In [132]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [133]:
print(a+2) # Also can use a += 2 to add 2 to each element of the array a
print(a-2) # Also can use a -= 2 to subtract 2 from each element of the array a
print(a*2) # Also can use a *= 2 to multiply each element of the array a by 2
print(a/2) # Also can use a /= 2 to divide each element of the array a by 2
print(a**2) # It is the same as a*a, which multiplies each element of the array a by itself, resulting in an array where each element is the square of the corresponding element in a.

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [134]:
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

# Take sin & cos of all the values
print(np.sin(a))
print(np.cos(a))
print(np.sin(b))
print(np.cos(b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[-0.95892427 -0.2794155   0.6569866   0.98935825]
[ 0.28366219  0.96017029  0.75390225 -0.14550003]


There are more things you can explore here: https://numpy.org/doc/2.4/reference/routines.math.html

### **Linear Algebra**

In [135]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

c = np.identity(3)

print(np.matmul(a,b)) # Matrix multiplication of a and b

print(np.linalg.det(c)) # Determinant of c

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
1.0


There are more things in LA.

To learn more about LA in NumPy you can refer this: https://numpy.org/doc/stable/reference/routines.linalg.html

### **STATISTICS**

In [136]:
stats = np.array([[1,2,3],[4,5,6],[7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
print(np.min(stats, axis=0)) # Minimum value in the array
print(np.min(stats, axis=1))
print(np.min(stats)) # Minimum value in the entire array

print(np.max(stats, axis=0)) # Maximum value in the array
print(np.max(stats, axis=1))
print(np.max(stats)) # Maximum value in the entire array

[1 2 3]
[1 4 7]
1
[7 8 9]
[3 6 9]
9


In [138]:
print(np.sum(stats)) # Sum of all the values in the array
print(np.sum(stats, axis=0)) # Sum of each column
print(np.sum(stats, axis=1)) # Sum of each row

45
[12 15 18]
[ 6 15 24]


### **REORGANIZING ARRAYS**

In [139]:
before = np.array([[1,2,3], [4,5,6]])
print(before)

after = before.reshape((3,2)) # Reshape the array to have 3 rows and 2 columns (Total elements after reshape should be the same as before)
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [140]:
# Vertically Stacking Vectors

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(np.vstack((v1,v2))) # Stack v1 and v2 vertically to create a 2D array with 2 rows and 3 columns
print(np.vstack((v1,v2,v1,v2))) # Stack v1 and v2 vertically to create a 2D array with 4 rows and 3 columns

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [141]:
# Horizontal Stacking Vectors

print(np.hstack((v1,v2))) # Stack v1 and v2 horizontally to create a 1D array with 6 elements
print(np.stack((v1,v2), axis=1)) # Stack v1 and v2 along a new axis (axis=1) to create a 2D array with 3 rows and 2 columns, where the first column contains the elements of v1 and the second column contains the elements of v2

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


### **MISCELLANEOUS THINGS**

#### **Load Data From File**

In [142]:
filedata = np.genfromtxt('data.txt', delimiter=',') # Load data from a text file, where each line is a row and values are separated by commas
print(filedata) # Print the loaded data from the text file, which is now stored in the variable filedata as a NumPy array.
print(filedata.astype('int32')) # Convert the data to integers and print it

print(filedata) # Print the original filedata to show that it is still in its original data type (probably float64) and has not been changed by the astype method, which returns a new array with the specified data type but does not modify the original array.

filedata = filedata.astype('int32') # Convert the data to integers and store it back in filedata
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


#### **Boolean Masking and Advanced Indexing**

In [143]:
filedata > 30 # This will return a boolean array of the same shape as filedata, where each element is True if the corresponding element in filedata is greater than 30, and False otherwise.

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [144]:
filedata[filedata >30] # This will return an array containing only the elements of filedata that are greater than 30. The boolean array from the previous step is used to filter the original data, resulting in an array of values that meet the condition.

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50], dtype=int32)

#### np.any()

Returns True if at least one element satisfies the condition.

axis=0 → check columns

axis=1 → check rows

In [145]:
np.any(filedata > 45, axis=0) # This will return a boolean array indicating whether any element in each column of filedata is greater than 45.

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [146]:
np.any(filedata > 45, axis=1) # This will return a boolean array indicating whether any element in each row of filedata is greater than 45.

array([False, False, False, False,  True])

#### np.all()

Returns True if all the element satisfies the condition.

In [147]:
np.all(filedata > 8, axis=0) # This will return a boolean array indicating whether all elements in each column of filedata are greater than 8.

array([False, False, False, False, False, False, False, False,  True,
        True])

In [148]:
np.all(filedata > 20, axis=1) # This will return a boolean array indicating whether all elements in each row of filedata are greater than 8.

array([False, False,  True,  True,  True])

In [149]:
((filedata > 15) & (filedata < 45)) # This will return a boolean array indicating whether each element in filedata is greater than 15 and less than 45.

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False, False,
        False]])

In [150]:
~((filedata > 15) & (filedata < 45)) # This will return a boolean array indicating whether each element in filedata is NOT greater than 15 and less than 45.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True]])

### *NOTE*
We can index with a list in NumPy

In [151]:
r = np.array([1,2,3,4,5,6,7,8,9])
r[[1,3,7]] # This will return an array containing the elements at index 1, 3, and 7 of the array r.

array([2, 4, 8])

### **Exercise 2**
1) There is a 5x5 matrix given below. You have to print the elements [[21, 22], [26, 27]].

In [152]:
matrix = np.array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(matrix)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [153]:
# Solution 1
matrix[2:4, 0:2] # This will return a subarray of matrix containing the rows from index 2 to 3 (inclusive) and columns from index 0 to 1 (inclusive). The resulting subarray will have the shape (2, 2) and will include the elements [[21, 22], [26, 27]].

array([[21, 22],
       [26, 27]])

2) From the same matrix above print elements [12,18,24,30]

In [154]:
# Solution 2
matrix[[0,1,2,3],[1,2,3,4]] # This will return an array containing the elements at the specified row and column indices of the matrix. The resulting array will include the elements [12, 18, 24, 30] from the matrix.

array([12, 18, 24, 30])

3) From the same matrix above print elements [14,15][29,30][34,35]

In [155]:
# Solution 3
matrix[[0,3,4]][:, 3:5] # This will return a subarray of matrix containing the rows at index 0, 3, and 4, and columns from index 3 to 4 (inclusive).

array([[14, 15],
       [29, 30],
       [34, 35]])