# **NumPy for Machine Learning**

Author: **Rupak Ganvir**

## **Importing NumPy**

In [1]:
import numpy as np

## **Basics**

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3,7],[4,5,6,8]])
print(b)

[[1 2 3 7]
 [4 5 6 8]]


In [4]:
# Dimension of an array

print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Shape of an array

print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [6]:
# Data type

print(a.dtype)
print(b.dtype)

int32
int64


In [7]:
# Get size

print(a.itemsize)
print(b.itemsize)

4
8


In [8]:
# Get total size

print(a.nbytes)
print(b.nbytes)

12
64


## **Accessing/Changing specific elements, rows, columns, etc**

In [9]:
n = np.array([[1,2,3,7,8,9,10],[4,5,6,8,11,12,13]])
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6  8 11 12 13]]


In [10]:
# Get a specific element

n[0, 2]
n[1, -5]

np.int64(6)

In [11]:
# Get a specific row

n[1, :]

array([ 4,  5,  6,  8, 11, 12, 13])

In [12]:
# Get a specific column

n[:, 1]

array([2, 5])

In [13]:
# Getting more complicated thing (startIndex:endIndex:stepSize)

n[0, 1:-1:2] # Get the first row, starting from index 1 to the end, with a step size of 2

array([2, 7, 9])

In [14]:
# Change any element

n[1,3] = 14
print(n)


# Change columns

n[:,2] = 1
print(n)
# or
n[:,2] = [11,22]
print(n)


# Change rows

n[1,:] = 1
print(n)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6 14 11 12 13]]
[[ 1  2  1  7  8  9 10]
 [ 4  5  1 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 4  5 22 14 11 12 13]]
[[ 1  2 11  7  8  9 10]
 [ 1  1  1  1  1  1  1]]


In [15]:
# 3D array

m = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
# Get a specific element

print(m[1,1,1]) # In 1st row, 1st column, 1st element (Indexing starts from 0)
print(m[:,1,:]) # Get the 1st column of all rows
print(m[:,1,:2]) # Get the 1st column of all rows, but only the first 2 elements

11
[[ 4  5  6]
 [10 11 12]]
[[ 4  5]
 [10 11]]


In [17]:
# Replace

m[:,1,:] = 20
print(m)

m[:,1,:] = [21,22,23]
print(m)

[[[ 1  2  3]
  [20 20 20]]

 [[ 7  8  9]
  [20 20 20]]]
[[[ 1  2  3]
  [21 22 23]]

 [[ 7  8  9]
  [21 22 23]]]


## **Initializing different types of arrays**

In [18]:
# All zeroes

print(np.zeros(5)) # 1D array of zeros
print(np.zeros((5,5))) # 2D array of zeros
print(np.zeros((2,2,3))) # 3D array of zeros

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
# All ones

print(np.ones(5)) # 1D array of ones
print(np.ones((5,5))) # 2D array of ones
print(np.ones((3,2,2))) # 3D array of ones

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [20]:
# Any other number

print(np.full((5,5), 99)) # 2D array of 99s
print(np.full((5,5), 3.14)) # 2D array of 3.14s
print(np.full((2,3,4), 99)) # 3D array of 99s


# Full_like
print(np.full_like(m,4)) # Create an array with the same shape as m, but filled with 4s

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[[[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]

 [[99 99 99 99]
  [99 99 99 99]
  [99 99 99 99]]]
[[[4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]]]


In [21]:
# Random Decimal Numbers

print(np.random.rand(4,2,3)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

print(np.random.random_sample(a.shape)) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). The shape is taken from array a.

[[[0.37825558 0.6395527  0.32061853]
  [0.72505063 0.96357927 0.30767139]]

 [[0.31290429 0.50864943 0.57980237]
  [0.68199659 0.7674997  0.44096555]]

 [[0.00508473 0.46460729 0.50829318]
  [0.95023874 0.33186742 0.52534275]]

 [[0.10721719 0.27690438 0.58236179]
  [0.87491768 0.08326454 0.15643627]]]
[0.74620524 0.09633216 0.81525801]


In [22]:
# Random Integer Value

print(np.random.randint(7, size =(3,3))) # Create an array of the given shape and populate it with random integers from 0 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.
print(np.random.randint(-2,7, size =(3,3))) # Create an array of the given shape and populate it with random integers from -2 to 6 (exclusive). The size is specified as a tuple (3,3) for a 3x3 array.

[[3 2 2]
 [4 6 4]
 [6 2 3]]
[[ 5 -1  5]
 [ 0  4  2]
 [ 3  0  3]]


#### **Random Seed**

By default, NumPy generates different random numbers every time you run the code. Setting a seed makes the results reproducible, meaning you will get the same random numbers every time. This is very important in ML experiments so that results can be compared and reproduced.

In [23]:
# Setting a random seed for reproducibility

np.random.seed(42) # 42 is just a convention, you can use any integer
print(np.random.randint(0, 10, size=(3,3))) # This will always give the same output

np.random.seed(42) # Reset the seed
print(np.random.randint(0, 10, size=(3,3))) # Same output as above because seed is same

[[6 3 7]
 [4 6 9]
 [2 6 7]]
[[6 3 7]
 [4 6 9]
 [2 6 7]]


In [24]:
# Identity matrix

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Repeat an array

arr = np.array([[1,2,3]]) # Create a 2D array with one row and three columns. The shape of this array is (1, 3), meaning it has 1 row and 3 columns. The elements of the array are 1, 2, and 3.

r1 = np.repeat(arr,3) # Repeat each element of arr 3 times. Since arr is a 2D array with shape (1, 3), the repeat function will flatten it to a 1D array and repeat each element 3 times, resulting in a 1D array with 9 elements: [1, 1, 1, 2, 2, 2, 3, 3, 3].
print(r1)

r2 = np.repeat(arr,3, axis=0) # Repeat each element of arr 3 times along the first axis (rows)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


### **Exercise 1**
1) Make a 5x5 array with all outer elements are one and inner elements are zero and the center element is 9

In [26]:
# Solution :
output = np.ones((5, 5), dtype='int32') # Create a 5x5 array filled with ones, with data type int32
output[1:4, 1:4] = 0 # Set the inner 3x3 block to zero
output[2, 2] = 9 # Set the center element to 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [27]:
# Be careful while copying arrays

a = np.array([1,2,3])
b = a # This does not create a new array, but rather a reference to the same array in memory. Changes to b will affect a and vice versa.
b[0] = 5
print(b)
print(a) # This will also show the change because b is a reference to a

# So the right way to copy:
a = np.array([1,2,3])
b = a.copy()
b[0] = 5
print(b)
print(a)

[5 2 3]
[5 2 3]
[5 2 3]
[1 2 3]


## **MATHEMATICS**

In [28]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [29]:
print(a+2) # Also can use a += 2 to add 2 to each element of the array a
print(a-2) # Also can use a -= 2 to subtract 2 from each element of the array a
print(a*2) # Also can use a *= 2 to multiply each element of the array a by 2
print(a/2) # Also can use a /= 2 to divide each element of the array a by 2
print(a**2) # It is the same as a*a, which multiplies each element of the array a by itself, resulting in an array where each element is the square of the corresponding element in a.

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [30]:
b = np.array([5,6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

# Take sin & cos of all the values
print(np.sin(a))
print(np.cos(a))
print(np.sin(b))
print(np.cos(b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[-0.95892427 -0.2794155   0.6569866   0.98935825]
[ 0.28366219  0.96017029  0.75390225 -0.14550003]


There are more things you can explore here: https://numpy.org/doc/2.4/reference/routines.math.html

### **np.where() — Conditional Selection**

np.where(condition, value_if_true, value_if_false) works like a vectorized if-else. It goes through each element of the array and applies the condition, returning value_if_true where the condition is True and value_if_false where it is False.

This is used very commonly in ML for things like implementing activations (ReLU), clipping gradients, or replacing invalid values.

In [31]:
a = np.array([1, -2, 3, -4, 5])

# Replace negative values with 0 (this is exactly how ReLU activation works)
result = np.where(a > 0, a, 0) # If element > 0, keep it, otherwise replace with 0
print(result)

[1 0 3 0 5]


In [32]:
# np.where with two arrays (choose element from x or y based on condition)

x = np.array([10, 20, 30, 40, 50])
y = np.array([1, 2, 3, 4, 5])

result = np.where(x > 25, x, y) # Where x > 25, take from x, otherwise take from y
print(result)

[ 1  2 30 40 50]


In [33]:
# np.where with only condition (returns indices where condition is True)

a = np.array([10, 20, 30, 40, 50])

indices = np.where(a > 25) # Returns a tuple of arrays containing the indices where condition is True
print(indices)
print(a[indices]) # Use those indices to get the actual values

(array([2, 3, 4]),)
[30 40 50]


### **Sorting**

np.sort() returns a sorted copy of the array. np.argsort() returns the indices that would sort the array — this is especially useful when you want to know the rank or position of each element.

In [34]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Sort the array (returns a sorted copy, original is unchanged)
print(np.sort(a)) # Ascending by default
print(np.sort(a)[::-1]) # Descending (reverse the sorted array)
print(a) # Original is unchanged

[1 1 2 3 4 5 6 9]
[9 6 5 4 3 2 1 1]
[3 1 4 1 5 9 2 6]


In [35]:
# argsort() → returns the indices that would sort the array

a = np.array([30, 10, 50, 20, 40])

sorted_indices = np.argsort(a) # Index of smallest → index of largest
print(sorted_indices) # [1 3 0 4 2] → element at index 1 is smallest, index 2 is largest
print(a[sorted_indices]) # Using those indices to sort the array

[1 3 0 4 2]
[10 20 30 40 50]


In [36]:
# Sorting a 2D array along an axis

m = np.array([[3,1,2],[9,7,8],[6,4,5]])
print(m)

print(np.sort(m, axis=1)) # Sort each row
print(np.sort(m, axis=0)) # Sort each column

[[3 1 2]
 [9 7 8]
 [6 4 5]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[3 1 2]
 [6 4 5]
 [9 7 8]]


### **np.unique() and np.bincount()**

np.unique() returns the unique elements of an array. np.bincount() counts how many times each integer value appears — useful for counting class occurrences in classification problems.

In [37]:
a = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Get unique values
print(np.unique(a)) # Returns sorted unique elements

# Get unique values along with how many times each appears
values, counts = np.unique(a, return_counts=True)
print(values) # Unique elements
print(counts) # How many times each unique element appears

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [38]:
# np.bincount() → counts how many times each integer from 0 to max(a) appears

labels = np.array([0, 1, 1, 2, 2, 2, 0, 1, 0]) # Class labels in a dataset

print(np.bincount(labels)) # [3 3 3] → class 0 appears 3 times, class 1 appears 3 times, class 2 appears 3 times

# This is useful in ML to check if your dataset is balanced or imbalanced

[3 3 3]


### **Linear Algebra**

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

c = np.identity(3)

print(np.matmul(a,b)) # Matrix multiplication of a and b

print(np.linalg.det(c)) # Determinant of c

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
1.0


#### **More Linear Algebra Operations**

NumPy's linalg module has many more useful operations for ML and scientific computing.

In [40]:
# Inverse of a matrix

a = np.array([[1, 2],[3, 4]])

inv_a = np.linalg.inv(a) # The inverse of a matrix A is the matrix A_inv such that A @ A_inv = Identity matrix
print(inv_a)

# Verify: A @ A_inv should give identity matrix
print(np.round(a @ inv_a)) # np.round() to remove floating point noise

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [41]:
# Eigenvalues and Eigenvectors

# Eigenvalues and eigenvectors are used in PCA (Principal Component Analysis) which is a very common
# dimensionality reduction technique in ML

a = np.array([[4, 2],[1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [42]:
# Singular Value Decomposition (SVD)

# SVD decomposes a matrix A into three matrices: U, S, Vt such that A = U @ diag(S) @ Vt
# It is used in PCA, image compression, and recommendation systems

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

U, S, Vt = np.linalg.svd(a)
print("U:\n", np.round(U, 2))
print("S (singular values):", np.round(S, 2)) # Singular values tell us how much variance each component captures
print("Vt:\n", np.round(Vt, 2))

U:
 [[-0.21  0.89  0.41]
 [-0.52  0.25 -0.82]
 [-0.83 -0.39  0.41]]
S (singular values): [16.85  1.07  0.  ]
Vt:
 [[-0.48 -0.57 -0.67]
 [-0.78 -0.08  0.63]
 [-0.41  0.82 -0.41]]


In [43]:
# Norm of a vector or matrix

# The norm is the "length" or "magnitude" of a vector. It is used in regularization (L1, L2),
# gradient clipping, and measuring distances

a = np.array([3.0, 4.0])

print(np.linalg.norm(a)) # L2 norm (Euclidean distance): sqrt(3^2 + 4^2) = 5.0
print(np.linalg.norm(a, ord=1)) # L1 norm: |3| + |4| = 7.0

# Norm of a matrix (Frobenius norm by default)
m = np.array([[1,2],[3,4]])
print(np.linalg.norm(m)) # sqrt(1^2 + 2^2 + 3^2 + 4^2)

5.0
7.0
5.477225575051661


There are more things in LA.

To learn more about LA in NumPy you can refer this: https://numpy.org/doc/stable/reference/routines.linalg.html

### **STATISTICS**

In [44]:
stats = np.array([[1,2,3],[4,5,6],[7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
print(np.min(stats, axis=0)) # Minimum value in the array
print(np.min(stats, axis=1))
print(np.min(stats)) # Minimum value in the entire array

print(np.max(stats, axis=0)) # Maximum value in the array
print(np.max(stats, axis=1))
print(np.max(stats)) # Maximum value in the entire array

[1 2 3]
[1 4 7]
1
[7 8 9]
[3 6 9]
9


In [46]:
print(np.sum(stats)) # Sum of all the values in the array
print(np.sum(stats, axis=0)) # Sum of each column
print(np.sum(stats, axis=1)) # Sum of each row

45
[12 15 18]
[ 6 15 24]


### **np.clip()**

np.clip() limits (clips) the values in an array to a specified range [min, max]. Any value below min becomes min, and any value above max becomes max. This is commonly used in ML to prevent values from going out of a valid range (e.g. keeping probabilities between 0 and 1 to avoid log(0) errors in loss functions).

In [47]:
a = np.array([-3, -1, 0, 2, 5, 8, 10])

# Clip values to the range [0, 6]
clipped = np.clip(a, 0, 6) # Values below 0 become 0, values above 6 become 6
print(clipped)

[0 0 0 2 5 6 6]


In [48]:
# Common use case: clipping predicted probabilities before computing log loss

probs = np.array([0.0, 0.2, 0.8, 1.0]) # Model output probabilities

# np.log(0) is -inf which will cause NaN in loss calculation
# So we clip to a small range to avoid this
safe_probs = np.clip(probs, 1e-7, 1 - 1e-7)
print(safe_probs)
print(np.log(safe_probs)) # No -inf now

[1.000000e-07 2.000000e-01 8.000000e-01 9.999999e-01]
[-1.61180957e+01 -1.60943791e+00 -2.23143551e-01 -1.00000005e-07]


### **Handling NaN Values**

NaN (Not a Number) represents missing or undefined values. Regular NumPy functions like np.mean() return NaN if even one element in the array is NaN. NumPy provides special nan-safe versions of these functions that skip NaN values.

In [49]:
a = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# Regular functions return NaN if any element is NaN
print(np.mean(a)) # nan
print(np.sum(a))  # nan

nan
nan


In [50]:
# nan-safe functions ignore NaN values and compute on the rest

print(np.nanmean(a))  # Mean ignoring NaN
print(np.nansum(a))   # Sum ignoring NaN
print(np.nanmin(a))   # Min ignoring NaN
print(np.nanmax(a))   # Max ignoring NaN
print(np.nanstd(a))   # Standard deviation ignoring NaN

3.25
13.0
1.0
6.0
1.920286436967152


In [51]:
# Check which elements are NaN

print(np.isnan(a)) # Returns a boolean array, True where element is NaN

# Count how many NaN values are present
print(np.isnan(a).sum()) # 2 NaN values

# Get the non-NaN values
print(a[~np.isnan(a)]) # ~ is the NOT operator, so this gives elements where isnan is False

[False False  True False  True False]
2
[1. 2. 4. 6.]


### **REORGANIZING ARRAYS**

In [52]:
# Reshape the array

before = np.array([[1,2,3], [4,5,6]])
print(before)

after = before.reshape((3,2)) # Reshape the array to have 3 rows and 2 columns (Total elements after reshape should be the same as before)
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [53]:
# Flatten array (Convert a multi-dimensional array into a 1D array)

a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

b = a.flatten() # It creates the copy

print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [54]:
# Ravel array

a = np.array([
    [1,2],
    [3,4]
])

print(a)

b = a.ravel() # ravel() → View (when possible)

print(b)

[[1 2]
 [3 4]]
[1 2 3 4]


In [55]:
# Difference between flatten() and ravel()

a = np.array([
    [1,2],
    [3,4]
])

flat = a.flatten() # makes a different copy in different location and flatten it
rav = a.ravel() # doesn't make a copy, make changes in the same location as a

flat[0] = 100 # make 0th index equal to 100 in the copy so a won't change
rav[1] = 200 # make 1st index equal to 200 in the rev whichj stores the value to the same memory location as a, so we will see the changes in the a array also

print(a,"\n")

print(flat,"\n")

print(rav,"\n")

[[  1 200]
 [  3   4]] 

[100   2   3   4] 

[  1 200   3   4] 



### **np.expand_dims() and np.squeeze()**

These two functions add or remove dimensions of size 1 from an array. This is very important in deep learning because models often expect input in a specific shape like (batch_size, channels, height, width). You frequently need to add or remove a dimension to match the expected shape.

In [56]:
a = np.array([1,2,3,4,5]) # Shape: (5,)
print("Original shape:", a.shape)

# Add a new axis at position 0 → makes it a row vector
b = np.expand_dims(a, axis=0) # Shape: (1, 5)
print("After expand_dims at axis=0:", b.shape)
print(b)

# Add a new axis at position 1 → makes it a column vector
c = np.expand_dims(a, axis=1) # Shape: (5, 1)
print("After expand_dims at axis=1:", c.shape)
print(c)

Original shape: (5,)
After expand_dims at axis=0: (1, 5)
[[1 2 3 4 5]]
After expand_dims at axis=1: (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [57]:
# np.squeeze() → removes dimensions of size 1

a = np.array([[[1,2,3]]]) # Shape: (1, 1, 3)
print("Original shape:", a.shape)

b = np.squeeze(a) # Removes all size-1 dimensions → Shape: (3,)
print("After squeeze:", b.shape)
print(b)

# You can also squeeze a specific axis
c = np.squeeze(a, axis=0) # Only remove axis 0 → Shape: (1, 3)
print("After squeeze at axis=0:", c.shape)

Original shape: (1, 1, 3)
After squeeze: (3,)
[1 2 3]
After squeeze at axis=0: (1, 3)


In [58]:
# Common use case in deep learning: adding batch dimension

# Suppose you have a single image of shape (28, 28) (like MNIST)
image = np.random.rand(28, 28)
print("Image shape:", image.shape)

# A model expects input of shape (batch_size, height, width), so we add the batch dimension
image_batch = np.expand_dims(image, axis=0) # Shape: (1, 28, 28)
print("After expand_dims (adding batch dim):", image_batch.shape)

Image shape: (28, 28)
After expand_dims (adding batch dim): (1, 28, 28)


In [59]:
# Vertically Stacking Vectors

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(np.vstack((v1,v2))) # Stack v1 and v2 vertically to create a 2D array with 2 rows and 3 columns
print(np.vstack((v1,v2,v1,v2))) # Stack v1 and v2 vertically to create a 2D array with 4 rows and 3 columns

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [60]:
# Horizontal Stacking Vectors

print(np.hstack((v1,v2))) # Stack v1 and v2 horizontally to create a 1D array with 6 elements
print(np.stack((v1,v2), axis=1)) # Stack v1 and v2 along a new axis (axis=1) to create a 2D array with 3 rows and 2 columns, where the first column contains the elements of v1 and the second column contains the elements of v2

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


### **np.concatenate() and np.split()**

np.concatenate() is the most general way to join arrays along an existing axis. np.split() does the opposite — it splits an array into multiple sub-arrays. These are very commonly used when preparing train/validation/test splits or combining dataset batches.

In [61]:
# np.concatenate() → joins arrays along an existing axis

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.concatenate((a,b), axis=0)) # Join along rows (one below the other)
print(np.concatenate((a,b), axis=1)) # Join along columns (side by side)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [62]:
# np.split() → splits an array into multiple sub-arrays

a = np.array([1,2,3,4,5,6,7,8,9,10])

# Split into 2 equal parts
parts = np.split(a, 2)
print(parts)

# Split at specific indices
parts = np.split(a, [3, 7]) # Split at index 3 and 7 → 3 parts: [0:3], [3:7], [7:]
print(parts)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


In [63]:
# Common use case: creating train/validation/test splits

data = np.arange(100) # Suppose we have 100 samples

# Split into 70% train, 20% validation, 10% test
train, val, test = np.split(data, [70, 90]) # Split at index 70 and 90
print("Train size:", len(train))
print("Val size:", len(val))
print("Test size:", len(test))

Train size: 70
Val size: 20
Test size: 10


### **MISCELLANEOUS THINGS**

#### **Load Data From File**

In [64]:
filedata = np.genfromtxt('data.txt', delimiter=',') # Load data from a text file, where each line is a row and values are separated by commas
print(filedata) # Print the loaded data from the text file, which is now stored in the variable filedata as a NumPy array.
print(filedata.astype('int32')) # Convert the data to integers and print it

print(filedata) # Print the original filedata to show that it is still in its original data type (probably float64) and has not been changed by the astype method, which returns a new array with the specified data type but does not modify the original array.

filedata = filedata.astype('int32') # Convert the data to integers and store it back in filedata
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


#### **Boolean Masking and Advanced Indexing**

In [65]:
filedata > 30 # This will return a boolean array of the same shape as filedata, where each element is True if the corresponding element in filedata is greater than 30, and False otherwise.

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [66]:
filedata[filedata >30] # This will return an array containing only the elements of filedata that are greater than 30. The boolean array from the previous step is used to filter the original data, resulting in an array of values that meet the condition.

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50], dtype=int32)

#### np.any()

Returns True if at least one element satisfies the condition.

axis=0 → check columns

axis=1 → check rows

In [67]:
np.any(filedata > 45, axis=0) # This will return a boolean array indicating whether any element in each column of filedata is greater than 45.

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
np.any(filedata > 45, axis=1) # This will return a boolean array indicating whether any element in each row of filedata is greater than 45.

array([False, False, False, False,  True])

#### np.all()

Returns True if all the element satisfies the condition.

In [69]:
np.all(filedata > 8, axis=0) # This will return a boolean array indicating whether all elements in each column of filedata are greater than 8.

array([False, False, False, False, False, False, False, False,  True,
        True])

In [70]:
np.all(filedata > 20, axis=1) # This will return a boolean array indicating whether all elements in each row of filedata are greater than 8.

array([False, False,  True,  True,  True])

In [71]:
((filedata > 15) & (filedata < 45)) # This will return a boolean array indicating whether each element in filedata is greater than 15 and less than 45.

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False, False, False,
        False]])

In [72]:
~((filedata > 15) & (filedata < 45)) # This will return a boolean array indicating whether each element in filedata is NOT greater than 15 and less than 45.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True]])

### *NOTE*
We can index with a list in NumPy

In [73]:
r = np.array([1,2,3,4,5,6,7,8,9])
r[[1,3,7]] # This will return an array containing the elements at index 1, 3, and 7 of the array r.

array([2, 4, 8])

### **Exercise 2**
1) There is a 5x5 matrix given below. You have to print the elements [[21, 22], [26, 27]].

In [74]:
matrix = np.array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(matrix)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [75]:
# Solution 1
matrix[2:4, 0:2] # This will return a subarray of matrix containing the rows from index 2 to 3 (inclusive) and columns from index 0 to 1 (inclusive). The resulting subarray will have the shape (2, 2) and will include the elements [[21, 22], [26, 27]].

array([[21, 22],
       [26, 27]])

2) From the same matrix above print elements [12,18,24,30]

In [76]:
# Solution 2
matrix[[0,1,2,3],[1,2,3,4]] # This will return an array containing the elements at the specified row and column indices of the matrix. The resulting array will include the elements [12, 18, 24, 30] from the matrix.

array([12, 18, 24, 30])

3) From the same matrix above print elements [14,15][29,30][34,35]

In [77]:
# Solution 3
matrix[[0,3,4]][:, 3:5] # This will return a subarray of matrix containing the rows at index 0, 3, and 4, and columns from index 3 to 4 (inclusive).

array([[14, 15],
       [29, 30],
       [34, 35]])

## **Broadcasting**

NumPy automatically stretches the smaller array so the operation can be performed.

In [78]:
arr1 = np.array([[1,2,3,4]])

print(arr1)

[[1 2 3 4]]


In [79]:
# Adding array with scalar

arr1 + 4

array([[5, 6, 7, 8]])

This shouldn't work but in broadcasting it makes the scalar 1x1 into 1x4 like arr1(1x4) so that they can match and add together. After stretching it will be like, arr1-> [[1 2 3 4]] and scalar 4 -> [[4 4 4 4]].

NumPy does not actually create [4 4 4 4]. That's why it is fast

In [80]:
# In 2D array with scalar

arr2 = np.array([[1,2],[2,3],[3,4],[4,5]])

print(arr2)

arr2 + 4

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


array([[5, 6],
       [6, 7],
       [7, 8],
       [8, 9]])

In 2D array with scalar value works same like 1D array, it just stretch the scalar value to match with the 2D array

In [81]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])

print(arr1)
print(arr2)

print(arr1.shape)
print(arr2.shape)

arr1 + arr2

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(1, 4)
(4, 1)


array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

So in this case arr1(1x4) stretches to 4x4 and arr2(4x1) stretches to 4x4 so that both should match

**Broadcasting Rules**

NumPy compares dimensions from right to left. Two dimensions are compatible if:
1. They are equal.
2. One of them is 1.

Otherwise it will show error.

In [82]:
# Example where the dimensions are not matching

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1],[2],[3],[4]])

print(arr1.shape)
print(arr2.shape)

# arr1 + arr2   -> This will give error

(2, 3)
(4, 1)


#### Exercise 3

arr1 = np.array([[1],[2],[3]])

arr2 = np.array([[10,20,30,40]])

Are these arrays compitible? If yes what will be the output of (arr1+arr2)

In [83]:
# Solution

arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[10,20,30,40]])

print(arr1.shape)
print(arr2.shape)

arr1 + arr2

(3, 1)
(1, 4)


array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

## **Transpose**

Convert rows into columns and columns into rows.

In [84]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [85]:
# Transpose of the matrix a

print(a.T)
print(a.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [86]:
# Another way to transpose the matrix

transpose = np.transpose(a)

print(transpose)
print(transpose.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [87]:
# Transpose and Matrix Multiplication

a = np.array([
    [1,2,3]
])
b = a.T

print(a.shape)
print(b.shape)

a@b

(1, 3)
(3, 1)


array([[14]])

In [88]:
# Transpose in 3D Arrays

a = np.random.randint(1,10,size=(2,3,4))

print(a)

print(a.shape)

b = np.transpose(a)

print(b)
print(b.shape)

[[[8 2 9 1]
  [8 4 4 5]
  [8 5 8 1]]

 [[9 6 3 8]
  [9 6 7 1]
  [5 5 4 6]]]
(2, 3, 4)
[[[8 9]
  [8 9]
  [8 5]]

 [[2 6]
  [4 6]
  [5 5]]

 [[9 3]
  [4 7]
  [8 4]]

 [[1 8]
  [5 1]
  [1 6]]]
(4, 3, 2)


In [89]:
# We can also specify axis

c = np.transpose(a, (1,0,2))  # Old axis 1 → New axis 0, Old axis 0 → New axis 1, Old axis 2 → New axis 2

print(c)

print(c.shape)

[[[8 2 9 1]
  [9 6 3 8]]

 [[8 4 4 5]
  [9 6 7 1]]

 [[8 5 8 1]
  [5 5 4 6]]]
(3, 2, 4)


## **np.einsum() — Einstein Summation**

np.einsum() provides a compact and elegant way to express many linear algebra operations using Einstein summation notation. The idea is simple: you describe the operation by specifying what happens to each index. It is used in research papers, deep learning implementations, and anywhere complex tensor operations are needed.

In [90]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Matrix multiplication using einsum
# 'ij,jk->ik' means: for each i and k, sum over j → this is exactly matrix multiplication
result = np.einsum('ij,jk->ik', a, b)
print(result)

# Verify with matmul
print(np.matmul(a, b)) # Should be same

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [91]:
# Transpose using einsum

a = np.array([[1,2,3],[4,5,6]])

# 'ij->ji' means: swap the i and j indices → transpose
print(np.einsum('ij->ji', a))
print(a.T) # Should be same

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [92]:
# Dot product of two vectors using einsum

a = np.array([1,2,3])
b = np.array([4,5,6])

# 'i,i->' means: multiply element-wise and sum everything → dot product
print(np.einsum('i,i->', a, b))
print(np.dot(a, b)) # Should be same

32
32


In [93]:
# Outer product of two vectors using einsum

a = np.array([1,2,3])
b = np.array([4,5,6])

# 'i,j->ij' means: for each pair (i,j), multiply a[i] * b[j] → outer product
print(np.einsum('i,j->ij', a, b))
print(np.outer(a, b)) # Should be same

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## Key Takeaways

- NumPy arrays are faster and more memory efficient than Python lists.
- Broadcasting enables operations on arrays with different shapes.
- Boolean masking allows efficient filtering.
- Reshaping and transposing help reorganize data for computation.
- np.where() enables vectorized conditional selection, useful for activations and masking.
- np.expand_dims() and np.squeeze() help manage dimensions when feeding data into ML models.
- np.linalg provides essential tools like SVD, eigendecomposition, and norms for ML and scientific computing.
- Always set a random seed (np.random.seed()) for reproducibility in experiments.
- Use nan-safe functions (np.nanmean, np.nansum etc.) when working with real-world data that may have missing values.
- NumPy forms the foundation of Pandas, Scikit-Learn, and Deep Learning libraries.